READING AND INCOMPLETE CSV

In [ ]:
import pandas as pd
df = pd.read_csv('stock_data.csv')
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

EXPORT THAT DF IN TO A NEW CSV (SPECIFYING THE COLUMNS AND ORDER)

In [ ]:
df.to_csv('stock2.csv',columns=['tickers','eps','revenue','price','people'])

In [ ]:
df2 = pd.read_excel('stock2.xlsx',skiprows=1,)
# df2 = pd.read_excel('stock2.xlsx',header=1,)
#usecols="B:E"
df2 = df2.drop(['Unnamed: 0'],axis='columns')
df2

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
df3 = pd.read_csv('stock3.csv',header=None, names=['ticker','eps','revenue','price','people'] ,sep=';')
df3

  ticker            eps  revenue price         people
0  GOOGL          27.82       87   845     larry page
1    WMT           4.61      484    65           n.a.
2   MSFT             -1       85    64     bill gates
3   RIL   not available       50  1023  mukesh ambani
4   TATA            5.6       -1  n.a.     ratan tata

In [ ]:
df = pd.read_csv('stock_data.csv', nrows=3)
df

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.
2    MSFT  -1.00       85     64  bill gates

READ CSV WITH NA VALUES

In [ ]:
df = pd.read_csv('stock_data.csv', na_values=['not available','n.a.'])
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82       87   845.0     larry page
1     WMT   4.61      484    65.0            NaN
2    MSFT  -1.00       85    64.0     bill gates
3    RIL     NaN       50  1023.0  mukesh ambani
4    TATA   5.60       -1     NaN     ratan tata

NA VALUES IN SPECIFIC COLUMNS

In [ ]:
df = pd.read_csv('stock_data.csv', na_values={
    'eps':['not available','n.a.'],
    'revenue':['not available','n.a.',-1],
    'people':['not available','n.a.'],
    'price':['not available','n.a.']
})
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT  -1.00     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

EXPORT CSV WITHOUT THE INDEX

In [ ]:
df.to_csv('new.csv',index=False,sep=';')

In [ ]:
#VERIFYING THE COLUMNS
df.columns

Index(['tickers', 'eps', 'revenue', 'price', 'people'], dtype='object')

In [ ]:
df.to_csv('new2.csv',columns=['tickers','eps'],index=False)

In [ ]:
df.to_csv('new.2.csv',header=False)

EXPORT DF TO EXCEL SPECIGYING THE SHEET NAME AND START COLUMNS AND ROWS

In [ ]:
df.to_excel('new.xlsx',sheet_name='stocks',startrow=1,startcol=2,index=False)
#

CREATING TWO DATAFRAMES FOR AN EXAMPLE

In [ ]:
import pandas as pd
import numpy as np

# DataFrame 1
data1 = {
    'col_A': np.random.randint(1, 100, 5),
    'col_B': np.random.rand(5).round(2),
    'col_C': ['apple', 'banana', 'orange', 'grape', 'kiwi']
}
df_random1 = pd.DataFrame(data1)
display(df_random1)

   col_A  col_B   col_C
0     95   0.77   apple
1     55   0.37  banana
2      6   0.94  orange
3     74   0.40   grape
4      6   0.17    kiwi

In [ ]:
# DataFrame 2
data2 = {
    'item': ['shirt', 'pants', 'shoes', 'hat'],
    'price': [25.99, 45.50, 70.00, 15.25],
    'in_stock': [True, False, True, True]
}
df_random2 = pd.DataFrame(data2)
display(df_random2)

    item  price  in_stock
0  shirt  25.99      True
1  pants  45.50     False
2  shoes  70.00      True
3    hat  15.25      True

WRITING 2 DF IN ONE EXCEL

In [ ]:
with pd.ExcelWriter('output.xlsx') as writer:
  df_random1.to_excel(writer, sheet_name='Sheet1', index=False)
  df_random2.to_excel(writer, sheet_name='Sheet2', index=False)

In [ ]:
import pandas as pd
stock_supermercado = [
    {"ID_Producto": 101, "Nombre": "Leche Entera 1L", "Categoria": "Lácteos", "Precio_Unitario": 1.20, "Cantidad_Stock": 50},
    {"ID_Producto": 102, "Nombre": "Pan de Molde", "Categoria": "Panadería", "Precio_Unitario": "not available", "Cantidad_Stock": 30},
    {"ID_Producto": 103, "Nombre": "Arroz Integral 1kg", "Categoria": "Abarrotes", "Precio_Unitario": 2.50, "Cantidad_Stock": 100},
    {"ID_Producto": 104, "Nombre": "Manzana Roja kg", "Categoria": "Frutas", "Precio_Unitario": 1.80, "Cantidad_Stock": "n.a."},
    {"ID_Producto": 105, "Nombre": "Detergente Líquido", "Categoria": "Limpieza", "Precio_Unitario": 12.50, "Cantidad_Stock": 15},
    {"ID_Producto": 106, "Nombre": "Huevos x12", "Categoria": "Lácteos", "Precio_Unitario": "n.a.", "Cantidad_Stock": 40},
    {"ID_Producto": 107, "Nombre": "Pasta Penne 500g", "Categoria": "Abarrotes", "Precio_Unitario": 0.95, "Cantidad_Stock": 85},
    {"ID_Producto": 108, "Nombre": "Aceite de Oliva", "Categoria": "not available", "Precio_Unitario": 7.30, "Cantidad_Stock": 20},
    {"ID_Producto": 109, "Nombre": "Yogurt Natural", "Categoria": "Lácteos", "Precio_Unitario": 0.60, "Cantidad_Stock": "n.a."},
    {"ID_Producto": 110, "Nombre": "Papel Higiénico 4pk", "Categoria": "Limpieza", "Precio_Unitario": 2.10, "Cantidad_Stock": 60}
]

df = pd.DataFrame(stock_supermercado)

df.to_excel('stock_supermercado.xlsx', sheet_name='Supermercado',startrow=1,startcol=2, index=False)