In [ ]:
import pandas as pd

Reas CSV

In [ ]:
df = pd.read_csv('weather_data.csv')
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

DataFrame from Dictionary

In [ ]:
weather_data = {
    'day': ['1/1/2026','1/2/2026','1/3/2026'],
    'temperature': [32,35,28],
    'windspeed': [6,7,2],
    'event': ['Rain','Sunny','Snow']
}
df2 = pd.DataFrame(weather_data)
df2

        day  temperature  windspeed  event
0  1/1/2026           32          6   Rain
1  1/2/2026           35          7  Sunny
2  1/3/2026           28          2   Snow

In [ ]:
df.shape

(6, 4)

In [ ]:
rows, cols = df.shape
rows

6

In [ ]:
cols

4

In [ ]:
df.head()

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [ ]:
df.tail()

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

Show Especific Rows or Data

In [ ]:
df[2:5]

        day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow
4  1/5/2017           32          4  Rain

Specific Column

In [ ]:
df['day']

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [ ]:
df.temperature

0    32
1    35
2    28
3    24
4    32
5    31
Name: temperature, dtype: int64

Show Columns

In [ ]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [ ]:
type(df['event'])

pandas.core.series.Series

Show 2 o More Columns

In [ ]:
df[['event','day']]

   event       day
0   Rain  1/1/2017
1  Sunny  1/2/2017
2   Snow  1/3/2017
3   Snow  1/4/2017
4   Rain  1/5/2017
5  Sunny  1/6/2017

OPERATIONS

In [ ]:
df.temperature.max()

35

In [ ]:
df.temperature.min()

24

In [ ]:
df.temperature.mean()

np.float64(30.333333333333332)

In [ ]:
df.temperature.std()

3.8297084310253524

Description of DataSet

In [ ]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

Show Data based in a Column Value

In [ ]:
df[df['temperature']>=32]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain

In [ ]:
df[df.temperature==df.temperature.max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [ ]:
df.day[df.temperature==df.temperature.max()]

1    1/2/2017
Name: day, dtype: object

In [ ]:
df[['day','temperature']][df.temperature==df.temperature.max()]

        day  temperature
1  1/2/2017           35

In [ ]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df.index

RangeIndex(start=0, stop=6, step=1)

Put a Column as the Index

In [ ]:
df.set_index('day')

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [ ]:
df.set_index('day', inplace=True)

In [ ]:
df

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

Search by Index Using LOC

In [ ]:
df.loc['1/3/2017']

temperature      28
windspeed         2
event          Snow
Name: 1/3/2017, dtype: object

In [ ]:
df.reset_index(inplace=True)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df.set_index('event',inplace=True)
df

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [ ]:
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7

In [ ]:
datos_clima = [
    {"fecha": "2026-02-01", "temperatura": 12, "velocidadvientos": 15, "clima": "Despejado"},
    {"fecha": "2026-02-02", "temperatura": 10, "velocidadvientos": 12, "clima": "Nublado"},
    {"fecha": "2026-02-03", "temperatura": 8, "velocidadvientos": 25, "clima": "Lluvia"},
    {"fecha": "2026-02-04", "temperatura": 7, "velocidadvientos": 30, "clima": "Tormenta"},
    {"fecha": "2026-02-05", "temperatura": 9, "velocidadvientos": 18, "clima": "Chubasco"},
    {"fecha": "2026-02-06", "temperatura": 11, "velocidadvientos": 10, "clima": "Bruma"},
    {"fecha": "2026-02-07", "temperatura": 13, "velocidadvientos": 8, "clima": "Soleado"},
    {"fecha": "2026-02-08", "temperatura": 14, "velocidadvientos": 12, "clima": "Despejado"},
    {"fecha": "2026-02-09", "temperatura": 12, "velocidadvientos": 20, "clima": "Viento"},
    {"fecha": "2026-02-10", "temperatura": 10, "velocidadvientos": 15, "clima": "Nublado"},
    {"fecha": "2026-02-11", "temperatura": 9, "velocidadvientos": 22, "clima": "Lluvia"},
    {"fecha": "2026-02-12", "temperatura": 11, "velocidadvientos": 14, "clima": "Nubes"},
    {"fecha": "2026-02-13", "temperatura": 13, "velocidadvientos": 9, "clima": "Despejado"},
    {"fecha": "2026-02-14", "temperatura": 15, "velocidadvientos": 11, "clima": "Soleado"},
    {"fecha": "2026-02-15", "temperatura": 16, "velocidadvientos": 13, "clima": "Despejado"},
    {"fecha": "2026-02-16", "temperatura": 14, "velocidadvientos": 19, "clima": "Cubierto"},
    {"fecha": "2026-02-17", "temperatura": 12, "velocidadvientos": 28, "clima": "Lluvia"},
    {"fecha": "2026-02-18", "temperatura": 11, "velocidadvientos": 24, "clima": "Llovizna"},
    {"fecha": "2026-02-19", "temperatura": 13, "velocidadvientos": 15, "clima": "Nublado"},
    {"fecha": "2026-02-20", "temperatura": 15, "velocidadvientos": 10, "clima": "Soleado"}
]

In [ ]:
import pandas as pd
df_clima = pd.DataFrame(datos_clima)
df_clima

         fecha  temperatura  velocidadvientos      clima
0   2026-02-01           12                15  Despejado
1   2026-02-02           10                12    Nublado
2   2026-02-03            8                25     Lluvia
3   2026-02-04            7                30   Tormenta
4   2026-02-05            9                18   Chubasco
5   2026-02-06           11                10      Bruma
6   2026-02-07           13                 8    Soleado
7   2026-02-08           14                12  Despejado
8   2026-02-09           12                20     Viento
9   2026-02-10           10                15    Nublado
10  2026-02-11            9                22     Lluvia
11  2026-02-12           11                14      Nubes
12  2026-02-13           13                 9  Despejado
13  2026-02-14           15                11    Soleado
14  2026-02-15           16                13  Despejado
15  2026-02-16           14                19   Cubierto
16  2026-02-17           12                28     Lluvia
17  2026-02-18           11                24   Llovizna
18  2026-02-19           13                15    Nublado
19  2026-02-20           15                10    Soleado

In [ ]:
df_clima.to_csv('clima_data.csv',index=False)