In [ ]:
import pandas as pd

READ FROM CSV

In [ ]:
df = pd.read_csv('weather_data.csv')
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

READ FROM EXCEL

In [ ]:
df = pd.read_excel('weather_data.xlsx','weather_data')

In [ ]:
df

  day,temperature,windspeed,event
0              1/1/2017,32,6,Rain
1             1/2/2017,35,7,Sunny
2              1/3/2017,28,2,Snow
3              1/4/2017,24,7,Snow
4              1/5/2017,32,4,Rain
5             1/6/2017,31,2,Sunny

CREATE DATA FRAME FROM DICTIONARY

In [ ]:
weather_data = {
    'day': ['1/1/2026','1/2/2026','1/3/2026'],
    'temperature': [32,35,28],
    'windspeed': [6,7,2],
    'event': ['Rain','Sunny','Snow']
}

In [ ]:
df = pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2026           32          6   Rain
1  1/2/2026           35          7  Sunny
2  1/3/2026           28          2   Snow

DF FROM TUPLE

In [ ]:
#From Tuple
weather_data = [
    ('1/1/2026',32,6,'Rain'),
    ('1/2/2026',35,7,'Sunny'),
    ('1/3/2026',28,2, 'Snow')
]

df = pd.DataFrame(weather_data, columns=['day','temperature','windspeed','event'])
df

        day  temperature  windspeed  event
0  1/1/2026           32          6   Rain
1  1/2/2026           35          7  Sunny
2  1/3/2026           28          2   Snow

DF FROM LIST OF DICTIONARIES

In [ ]:
#List of Dictionaries+

weather_data = [
    {'day': '1/1/2026', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/2/2026', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/3/2026', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},
]
df = pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2026           32          6   Rain
1  1/2/2026           35          7  Sunny
2  1/3/2026           28          2   Snow