READ CSV AND FORMATTING THE DATES

In [ ]:
import pandas as pd
df = pd.read_csv('weather_data.csv', parse_dates=['day'])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

CHEKING THE DATE FORMAT

In [ ]:
type(df.day[0])

pandas._libs.tslibs.timestamps.Timestamp

SETTING THE DAY AS AN INDEX

In [ ]:
df.set_index('day', inplace=True)
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

FILLNA WITH ZERO

In [ ]:
new_df = df.fillna(0)
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          0.0        9.0   Sunny
2017-01-05         28.0        0.0    Snow
2017-01-06          0.0        7.0       0
2017-01-07         32.0        0.0    Rain
2017-01-08          0.0        0.0   Sunny
2017-01-09          0.0        0.0       0
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

FILLNA WITH DIFFERENT VALUES

In [ ]:
new_df = df.fillna({
    'temperature': 0,
    'windspeed': 0,
    'event': 'no event'
})

new_df

            temperature  windspeed     event
day
2017-01-01         32.0        6.0      Rain
2017-01-04          0.0        9.0     Sunny
2017-01-05         28.0        0.0      Snow
2017-01-06          0.0        7.0  no event
2017-01-07         32.0        0.0      Rain
2017-01-08          0.0        0.0     Sunny
2017-01-09          0.0        0.0  no event
2017-01-10         34.0        8.0    Cloudy
2017-01-11         40.0       12.0     Sunny

FILLNA WITH FORWARD FILL

In [ ]:
new_df = df.fillna(method='ffill')
new_df

/tmp/ipython-input-4157630123.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df = df.fillna(method='ffill')

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        7.0   Sunny
2017-01-09         32.0        7.0   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

BACKWARD FILL

In [ ]:
new_df = df.fillna(method='bfill')
new_df

/tmp/ipython-input-2862997843.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df = df.fillna(method='bfill')

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        8.0    Rain
2017-01-08         34.0        8.0   Sunny
2017-01-09         34.0        8.0  Cloudy
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

BACKWARD FILL WITH AXIS COLUMNS

In [ ]:
new_df = df.fillna(method='bfill', axis='columns')
new_df

/tmp/ipython-input-3217195100.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df = df.fillna(method='bfill', axis='columns')
/tmp/ipython-input-3217195100.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_df = df.fillna(method='bfill', axis='columns')

           temperature windspeed   event
day
2017-01-01        32.0       6.0    Rain
2017-01-04         9.0       9.0   Sunny
2017-01-05        28.0      Snow    Snow
2017-01-06         7.0       7.0     NaN
2017-01-07        32.0      Rain    Rain
2017-01-08       Sunny     Sunny   Sunny
2017-01-09         NaN       NaN     NaN
2017-01-10        34.0       8.0  Cloudy
2017-01-11        40.0      12.0   Sunny

FORWARD FILL WITH JUST ONE FORWARD

In [ ]:
new_df = df.fillna(method='ffill', limit=1)
new_df

/tmp/ipython-input-353201514.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df = df.fillna(method='ffill', limit=1)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        NaN   Sunny
2017-01-09          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

COMPLETE NA WITH INTERPOLATE

In [ ]:
new_df = df.interpolate()
new_df

/tmp/ipython-input-812076388.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df = df.interpolate()

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    Rain
2017-01-04    30.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00     NaN
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75     NaN
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

INTERPOLATE BASED ON TIME

In [ ]:
new_df = df.interpolate(method='time')
new_df

/tmp/ipython-input-3316049018.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df = df.interpolate(method='time')

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    Rain
2017-01-04    29.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00     NaN
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75     NaN
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

DROPNA

In [ ]:
new_df = df.dropna()
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

DROPNA WITH ALL (JUST DROP THE COLUMNS WITH ALL NA VALUES)

In [ ]:
#Dropear las filas que tenga todos sus valores vacios
new_df = df.dropna(how='all')
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

KEEP THE ROWS WITH AT LEAST ONE NO N.A. VALUE

In [ ]:
#At least 1 no N.A. value keep it
new_df = df.dropna(thresh=1)
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
#I need at least 2 no N.A. Values
new_df = df.dropna(thresh=2)
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-07         32.0        NaN    Rain
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

CREATING NEW INDEX TO FILL THE MISSING DATES

In [ ]:
dt = pd.date_range('01-01-2017', '01-11-2017')
idx = pd.DatetimeIndex(dt)
df = df.reindex(idx)
df

            temperature  windspeed   event
2017-01-01         32.0        6.0    Rain
2017-01-02          NaN        NaN     NaN
2017-01-03          NaN        NaN     NaN
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

Esta línea crea un rango de fechas. `pd.date_range()` es una función de pandas que genera una secuencia de objetos `datetime`. En este caso, crea un rango de fechas que comienza el '01-01-2017' y termina el '01-11-2017' (ambos incluidos), con una frecuencia diaria por defecto.

**`dt = pd.date_range('01-01-2017', '01-11-2017')`**

Aquí, la secuencia de fechas `dt` que creaste en el paso anterior se convierte explícitamente en un objeto `pd.DatetimeIndex`. Aunque `date_range` ya suele devolver un DatetimeIndex, esta línea asegura que el tipo de índice sea el correcto.

**`idx = pd.DatetimeIndex(dt)`**

Finalmente, esta es la parte crucial. El método `reindex()` se usa para conformar un DataFrame a un nuevo índice. Lo que hace es lo siguiente:

1.  **Añade filas:** Si el nuevo índice (`idx`) contiene fechas que no estaban en el índice original de `df`, `reindex()` añade esas filas al DataFrame. Para los valores de las columnas en estas nuevas filas, pandas inserta `NaN` (Not a Number) o `NaT` (Not a Time) para indicar que no hay datos disponibles para esas fechas.
2.  **Mantiene filas:** Si una fecha del nuevo índice ya existía en el DataFrame original, los datos correspondientes a esa fecha se mantienen.
3.  **Elimina filas:** Si el DataFrame original tenía fechas en su índice que no están presentes en el nuevo índice `idx`, esas filas se eliminan del DataFrame resultante.

En resumen, estás creando un rango de fechas completo y luego le estás diciendo a tu DataFrame `df` que se "ajuste" a ese nuevo rango de fechas, rellenando los días faltantes con `NaN` si no había datos para ellos en el `df` original.

**`df = df.reindex(idx)`**

El método `time` utiliza los valores del índice de tiempo para estimar los valores faltantes. Por ejemplo, si tienes valores en el día 1 y el día 3, y falta un valor en el día 2, `time` considerará la distancia temporal entre estos puntos para hacer la interpolación, en lugar de simplemente la posición lineal. Esto es útil cuando los datos no están espaciados uniformemente en el tiempo.

En tu caso, después de ejecutar `df.set_index('day', inplace=True)`, el índice de tu DataFrame `df` se convirtió en un `DatetimeIndex`. Por lo tanto, cuando llamaste a `df.interpolate(method='time')`, pandas utilizó automáticamente este `DatetimeIndex` para realizar la interpolación basada en el tiempo.

Si el índice no fuera de tipo `DatetimeIndex`, `method='time'` generaría un error, ya que no tendría información temporal para basar la interpolación.