HANDLE MISSING DATA WITH REPLACE FUNCTION

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

REPLACE

In [ ]:
new_df = df.replace(-99999,np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

REPLACE ON SPECIFIC COLUMNS

In [ ]:
new_df = df.replace({
    'temperature':-99999,
    'windspeed':-99999,
    'event': '0'
},np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

REPLACE USING MAPPING DICTIONARY

In [ ]:
new_df = df.replace({
    -99999:np.nan,
    '0':'Sunny'
},np.nan)

new_df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

SEPARATING UNIT OF MEASURE FROM NUMBERS USING REGEX

In [ ]:
df2 = pd.read_csv("weather_data2.csv")
df2

        day temperature windspeed  event
0  1/1/2017        32 F     6 mph   Rain
1  1/2/2017      -99999         7  Sunny
2  1/3/2017        28 C    -99999   Snow
3  1/4/2017      -99999         7      0
4  1/5/2017          32    -99999   Rain
5  1/6/2017          31     2 mph  Sunny
6  1/6/2017          34         5      0

In [ ]:
new_df = df.replace('[A-Za-z]','',regex=True)
new_df

        day  temperature  windspeed event
0  1/1/2017           32          6
1  1/2/2017       -99999          7
2  1/3/2017           28     -99999
3  1/4/2017       -99999          7     0
4  1/5/2017           32     -99999
5  1/6/2017           31          2
6  1/6/2017           34          5     0

In [ ]:
new_df = df.replace({
    'temperature':'[A-Za-z]',
    'windspeed':'[A-Za-z]'
},'',regex=True)
new_df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

REPLACE A LIST OF VALUES WITH OTHER LIST OF VALUES

In [ ]:
df = pd.DataFrame({
    'score': ['exceptional','average','good','poor','average'],
    'student': ['bob','marc','carl','matt','kris']
})
df

         score student
0  exceptional     bob
1      average    marc
2         good    carl
3         poor    matt
4      average    kris

In [ ]:
new_df = df.replace(['exceptional','average','good','poor'],[4,2,3,1])
new_df

/tmp/ipykernel_258/1022148490.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_df = df.replace(['exceptional','average','good','poor'],[4,2,3,1])

   score student
0      4     bob
1      2    marc
2      3    carl
3      1    matt
4      2    kris